eeureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true 
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

      


spring:
  activemq:
     user: admin
     password: admin
     broker-url: tcp://localhost:61616?jms.redeliveryPolicy.maximumRedeliveries=1
     
userdomainserviceUrl: http://USERDOMAINSERVICE