eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: DEV_USER
    password: ankamma1
    driver-class-name: oracle.jdbc.driver.OracleDriver
   
    
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
  
  jpa:
    properties:
      hibernate:
        dialeact:org.hibernate.dialect.Oracle12cDialect
        show_sql:true
        format_sql:true
          