eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: DEV_USER
    password: ankamma1
    driver-class-name: oracle.jdbc.driver.OracleDriver
    

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
        ddl-auto: create,update
    show-sql: true
       
  
